#!/bin/bash

# CDK Outputs から .env ファイルを自動生成/更新するスクリプト
# デプロイ後に実行して環境変数を最新化

set -e

# カラー出力
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Syncing .env from CDK Outputs          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"
echo ""

# AWS Profile の確認
AWS_PROFILE="${AWS_PROFILE:-myblog-dev}"
echo -e "${YELLOW}Using AWS Profile: $AWS_PROFILE${NC}"
echo ""

# CDK Outputs を取得
echo -e "${BLUE}🔍 Fetching CDK Stack Outputs...${NC}"

# DataStack Outputs
echo -e "${BLUE}  - DataStack outputs${NC}"
DATA_STACK_OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name MyBlog-DataStack \
  --profile "$AWS_PROFILE" \
  --query 'Stacks[0].Outputs' \
  --output json 2>/dev/null)

if [ $? -ne 0 ] || [ -z "$DATA_STACK_OUTPUTS" ]; then
  echo -e "${RED}❌ Failed to get DataStack outputs${NC}"
  echo "Make sure the stack is deployed: cdk deploy MyBlog-DataStack"
  exit 1
fi

# AppStack Outputs
echo -e "${BLUE}  - AppStack outputs${NC}"
APP_STACK_OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name MyBlog-AppStack \
  --profile "$AWS_PROFILE" \
  --query 'Stacks[0].Outputs' \
  --output json 2>/dev/null)

if [ $? -ne 0 ] || [ -z "$APP_STACK_OUTPUTS" ]; then
  echo -e "${RED}❌ Failed to get AppStack outputs${NC}"
  echo "Make sure the stack is deployed: cdk deploy MyBlog-AppStack"
  exit 1
fi

echo -e "${GREEN}✅ Successfully fetched stack outputs${NC}"
echo ""

# Outputs から値を抽出
extract_output() {
  local outputs=$1
  local key=$2
  echo "$outputs" | jq -r ".[] | select(.OutputKey==\"$key\") | .OutputValue"
}

# DataStack の値を抽出
COGNITO_USER_POOL_ID=$(extract_output "$DATA_STACK_OUTPUTS" "UserPoolId")
COGNITO_CLIENT_ID=$(extract_output "$DATA_STACK_OUTPUTS" "UserPoolClientId")
DYNAMODB_TABLE_NAME=$(extract_output "$DATA_STACK_OUTPUTS" "TableName")
MEDIA_BUCKET_NAME=$(extract_output "$DATA_STACK_OUTPUTS" "MediaBucketName")
MEDIA_CLOUDFRONT_DOMAIN=$(extract_output "$DATA_STACK_OUTPUTS" "MediaDistributionDomainName")

# AppStack の値を抽出
API_URL=$(extract_output "$APP_STACK_OUTPUTS" "MyBlogApiEndpointC82E3489")
FRONTEND_BUCKET_NAME=$(extract_output "$APP_STACK_OUTPUTS" "FrontendBucketName")
FRONTEND_CLOUDFRONT_DOMAIN=$(extract_output "$APP_STACK_OUTPUTS" "DistributionDomainName")

# AWS_REGION を取得
AWS_REGION=$(aws configure get region --profile "$AWS_PROFILE" || echo "ap-northeast-1")

# 既存の .env ファイルから保持すべき値を読み込み
if [ -f "$ENV_FILE" ]; then
  echo -e "${BLUE}📄 Reading existing .env file...${NC}"
  source "$ENV_FILE" 2>/dev/null || true
fi

# バックアップを作成
if [ -f "$ENV_FILE" ]; then
  BACKUP_FILE="$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
  cp "$ENV_FILE" "$BACKUP_FILE"
  echo -e "${YELLOW}📦 Backup created: $BACKUP_FILE${NC}"
fi

# 新しい .env ファイルを生成
echo -e "${BLUE}✍️  Writing new .env file...${NC}"

cat > "$ENV_FILE" << EOF
# MyBlog Environment Configuration
# Auto-generated by scripts/sync-env.sh on $(date)
# ⚠️ Do not commit this file to Git!

# ==============================================
# AWS Configuration
# ==============================================
AWS_PROFILE=${AWS_PROFILE}
AWS_REGION=${AWS_REGION}

# ==============================================
# API Configuration
# ==============================================
API_URL=${API_URL}

# ==============================================
# Cognito Configuration
# ==============================================
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}

# ==============================================
# DynamoDB Configuration
# ==============================================
DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}

# ==============================================
# S3 & CloudFront Configuration
# ==============================================
# Media (User-uploaded content)
MEDIA_BUCKET_NAME=${MEDIA_BUCKET_NAME}
MEDIA_CLOUDFRONT_DOMAIN=${MEDIA_CLOUDFRONT_DOMAIN}

# Frontend (Website hosting)
FRONTEND_BUCKET_NAME=${FRONTEND_BUCKET_NAME}
FRONTEND_CLOUDFRONT_DOMAIN=${FRONTEND_CLOUDFRONT_DOMAIN}

# ==============================================
# Test User Credentials
# ==============================================
# Set your test user credentials here
TEST_USER_EMAIL=${TEST_USER_EMAIL:-your-email@example.com}
TEST_USER_PASSWORD=${TEST_USER_PASSWORD:-}

# ==============================================
# Optional: Manual JWT Token
# ==============================================
# If you want to use a manually obtained JWT token
# JWT_TOKEN=

# ==============================================
# Environment
# ==============================================
NODE_ENV=${NODE_ENV:-development}
EOF

echo -e "${GREEN}✅ .env file updated successfully!${NC}"
echo ""

# 結果を表示
echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║           Updated Configuration            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}AWS Configuration:${NC}"
echo "  AWS_PROFILE: $AWS_PROFILE"
echo "  AWS_REGION: $AWS_REGION"
echo ""
echo -e "${YELLOW}API:${NC}"
echo "  API_URL: $API_URL"
echo ""
echo -e "${YELLOW}Cognito:${NC}"
echo "  USER_POOL_ID: $COGNITO_USER_POOL_ID"
echo "  CLIENT_ID: $COGNITO_CLIENT_ID"
echo ""
echo -e "${YELLOW}DynamoDB:${NC}"
echo "  TABLE_NAME: $DYNAMODB_TABLE_NAME"
echo ""
echo -e "${YELLOW}S3 & CloudFront:${NC}"
echo "  MEDIA_BUCKET: $MEDIA_BUCKET_NAME"
echo "  MEDIA_CDN: $MEDIA_CLOUDFRONT_DOMAIN"
echo "  FRONTEND_BUCKET: $FRONTEND_BUCKET_NAME"
echo "  FRONTEND_CDN: $FRONTEND_CLOUDFRONT_DOMAIN"
echo ""

# 警告: パスワードの設定
if [ -z "$TEST_USER_PASSWORD" ] || [ "$TEST_USER_PASSWORD" == "" ]; then
  echo -e "${YELLOW}⚠️  Warning: TEST_USER_PASSWORD is not set${NC}"
  echo "Please edit .env and set your test user password:"
  echo "  vi .env"
  echo ""
fi

echo -e "${GREEN}🎉 Environment synchronization complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. Edit .env to set TEST_USER_PASSWORD if needed"
echo "  2. Run tests: ./tests/api-test.sh"
echo ""
